"use client";

import React from "react";
import PageHeader from "@/components/PageHeader";
import Link from "next/link";

export default function PrivacyPage() {
  return (
    <>
      <PageHeader
        title="Privacy Policy & Data Governance"
        subtitle="How CENTURIO DESIGNS Protects Your Private Architectural & Financial Data"
      />

      <div className="py-24 bg-gradient-to-b from-[#FAF8F5] via-[#F4EFE6] to-[#ECE5D8] text-charcoal">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 md:px-8 space-y-10">
          
          <div className="bg-white/90 backdrop-blur-md p-8 md:p-12 rounded-sm border border-gold/30 shadow-xl space-y-8">
            <div className="border-b border-gold/20 pb-4 flex items-center justify-between">
              <span className="text-gold font-mono text-xs tracking-widest uppercase">
                DOCUMENT VERIFICATION: REG-2026-PRIVACY
              </span>
              <span className="text-gray-500 font-mono text-xs">
                LAST UPDATED: SEPTEMBER 2026
              </span>
            </div>

            <section className="space-y-4">
              <h2 className="font-serif-luxury text-2xl text-[#181512]">1. Private Commission Confidentiality</h2>
              <p className="text-gray-700 text-sm leading-relaxed font-light">
                CENTURIO INTERIOR STUDIO operates under strict non-disclosure and privacy protocols for high-net-worth residential and commercial clients. All blueprints, site dimensions, financial budgets, and floorplan WebGL models remain 100% confidential and are never shared with un-vetted third parties.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="font-serif-luxury text-2xl text-[#181512]">2. Collection of Personal & Site Information</h2>
              <p className="text-gray-700 text-sm leading-relaxed font-light">
                We collect information directly provided by clients through our private consultation requests, 3D configurator sessions, and site audits. This includes client contact details, site location addresses, architectural preferences, and budget allocations necessary for executing turnkey contracts.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="font-serif-luxury text-2xl text-[#181512]">3. Digital Twin & WebGL Data Protection</h2>
              <p className="text-gray-700 text-sm leading-relaxed font-light">
                3D CAD blueprints, WebGL spatial renderings, and custom joinery models generated by our studio are encrypted and stored on isolated secure cloud servers. 3D spatial models are accessible only through authenticated client links during your commission timeline.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="font-serif-luxury text-2xl text-[#181512]">4. Data Retention & Client Rights</h2>
              <p className="text-gray-700 text-sm leading-relaxed font-light">
                Clients retain full rights to request complete deletion or physical handover of all architectural records upon project completion and warranty issuance. We do not sell or monetize client data under any circumstances.
              </p>
            </section>

            <div className="pt-6 border-t border-gold/20 flex flex-col sm:flex-row items-center justify-between gap-4">
              <span className="text-xs font-mono text-gray-500">
                Questions regarding privacy? Email privacy@centuriodesigns.com
              </span>
              <Link
                href="/"
                className="gold-bg text-white px-6 py-2.5 rounded-sm text-xs font-mono tracking-widest uppercase hover:shadow-lg transition-all"
              >
                Return to Studio Home
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
